# Generated by Django 3.2.25 on 2026-01-31 08:23

import create_document.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedDocument',
            fields=[
                ('doc_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Created Document ID')),
                ('document', models.FileField(blank=True, max_length=200, null=True, upload_to=create_document.models.get_tenant_specific_new_document)),
                ('document_name', models.CharField(blank=True, max_length=200, null=True)),
                ('doc_created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ac', 'Active'), ('ia', 'Inactive'), ('de', 'Deleted')], default='ac', max_length=2)),
                ('doc_type', models.CharField(choices=[('docx', 'docx'), ('pdf', 'pdf'), ('xlsx', 'xlsx'), ('dlf-xlsx', 'dlf-xlsx'), ('dlf-docx', 'dlf-docx')], default='pdf', max_length=20)),
                ('doc_updated_on', models.DateTimeField(auto_now=True)),
                ('doc_deleted_on', models.DateTimeField(blank=True, null=True)),
                ('doc_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('doc_group', models.ManyToManyField(blank=True, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_choice', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataKey',
            fields=[
                ('key_id', models.AutoField(primary_key=True, serialize=False)),
                ('metadata_key', models.CharField(max_length=100)),
                ('metadata_description', models.CharField(blank=True, max_length=200)),
                ('metadata_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('choice', 'Choice'), ('textarea', 'TextArea'), ('image', 'Image'), ('signature', 'Signature')], max_length=10)),
                ('external_metadata', models.BooleanField(default=False)),
                ('metadata_choice', models.ManyToManyField(blank=True, to='create_document.MetadataChoice')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('temp_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('template_flag', models.CharField(choices=[('docx', 'docx'), ('xlsx', 'xlsx'), ('dlf-xlsx', 'dlf-xlsx'), ('dlf-docx', 'dlf-docx')], default='docx', max_length=10)),
                ('temp_status', models.CharField(choices=[('ac', 'Active'), ('ia', 'Inactive'), ('de', 'Deleted'), ('pe', 'Pending')], default='pe', max_length=2)),
                ('temp_title', models.CharField(max_length=100)),
                ('temp_description', models.CharField(blank=True, max_length=400)),
                ('template', models.FileField(max_length=200, upload_to=create_document.models.get_tenant_specific_template)),
                ('temp_created_at', models.DateTimeField(auto_now_add=True)),
                ('temp_edited_on', models.DateTimeField(auto_now=True)),
                ('temp_deleted_on', models.DateTimeField(blank=True, null=True)),
                ('doc_group', models.ManyToManyField(blank=True, to='auth.Group')),
                ('temp_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_templates', to=settings.AUTH_USER_MODEL)),
                ('temp_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataValue',
            fields=[
                ('meta_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('metadata_value_text', models.TextField(blank=True, null=True)),
                ('metadata_value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('metadata_value_date', models.DateField(blank=True, null=True)),
                ('metadata_value_bool', models.BooleanField(null=True)),
                ('metadata_value_image', models.ImageField(blank=True, null=True, upload_to='metadata_images/')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('meta_created_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_document.createddocument')),
                ('meta_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_document.metadatakey')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='createddocument',
            name='doc_matched_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create_document.template'),
        ),
        migrations.CreateModel(
            name='TemplateMetaData',
            fields=[
                ('temp_meta_id', models.AutoField(primary_key=True, serialize=False)),
                ('temp_description', models.CharField(max_length=300)),
                ('metadata_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_document.metadatakey')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_document.template')),
            ],
            options={
                'unique_together': {('template', 'metadata_key')},
            },
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['temp_status'], name='create_docu_temp_st_b5d5c2_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['template_flag'], name='create_docu_templat_d50c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='metadatavalue',
            index=models.Index(fields=['meta_key'], name='create_docu_meta_ke_6471bc_idx'),
        ),
        migrations.AddIndex(
            model_name='metadatavalue',
            index=models.Index(fields=['meta_created_doc'], name='create_docu_meta_cr_82de7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metadatavalue',
            unique_together={('meta_key', 'meta_created_doc')},
        ),
        migrations.AddIndex(
            model_name='createddocument',
            index=models.Index(fields=['status'], name='create_docu_status_6ff2e8_idx'),
        ),
        migrations.AddIndex(
            model_name='createddocument',
            index=models.Index(fields=['doc_type'], name='create_docu_doc_typ_d03556_idx'),
        ),
        migrations.AddIndex(
            model_name='createddocument',
            index=models.Index(fields=['doc_created_at'], name='create_docu_doc_cre_43f0bf_idx'),
        ),
    ]
